# Usar imagem oficial do Node.js
FROM node:22

WORKDIR /usr/src/app

COPY iot-gateway/package*.json ./

RUN npm install

COPY iot-blockchain/test-network/organizations ./iot-blockchain/test-network/organizations

COPY iot-gateway/ .

EXPOSE 3001

CMD ["npm", "start"]