services:
  broker-mosquitto:
    image: eclipse-mosquitto:2.0
    ports:
      - "1883:1883"
    volumes:
      - ./broker/:/mosquitto/config/:ro
    networks:
      - iot-net
    restart: unless-stopped

  sim-mini-factory:
    build: .
    depends_on:
      - broker-mosquitto
    environment:
      BROKER_HOST: "broker-mosquitto"
      BROKER_PORT: "1883"
      SET_DELAY_BETWEEN_MESSAGES: "0.05"
      RANDOMIZE_DELAY_BETWEEN_MESSAGES: "false"
    networks:
      - iot-net


  mosquitto-client:
    image: eclipse-mosquitto:2.0
    entrypoint: [ "mosquitto_sub", "--host", "broker-mosquitto", "--port", "1883", "--topic", "plantA/#", "--verbose" ]
    depends_on:
      - broker-mosquitto    
    networks:
      - iot-net

networks:
  iot-net:
    driver: bridge
